Made changes based on recommendations by Neil and also fixed minor abstract rendering issues in a few other papers
mlresearch/v134 pull request #3
Opened 2021-08-02 05:05 UTC by sgunasekar

2021-08-02 06:37 UTC, lawrennd requested changes
Wow Suriya, great work on tidying up the maths. There's a couple of spots where we need html tags instead of latex though.

2021-08-02 06:37 UTC, lawrennd commented on _posts/2021-07-21-braverman21a.md
> +abstract: '{\em Distributed learning} protocols are designed to train on distributed data without gathering it all on a single centralized machine,
We can use latex foe maths in abstract, but need html for itlaics.

2021-08-02 06:37 UTC, lawrennd commented on _posts/2021-07-21-braverman21a.md
> +To this end, we introduce a new tool called {\em halfspace containers}, that is closely related to {\em bracketing numbers} in statistics and to {\it hyperplane cuttings} in discrete geometry,
HTML needed here.

2021-08-02 06:37 UTC, lawrennd commented on _posts/2021-07-21-lee21a.md
> +abstract: 'We give algorithms for sampling several structured logconcave families to high accuracy. We further develop a reduction framework, inspired by proximal point methods in convex optimization
Latex quotes in this abstract, use normal quotes

2021-08-04 17:21 UTC, sgunasekar commented
I fixed a couple more abstracts with math issues and the html tag issues raised by Neil.

2021-08-05 06:58 UTC, lawrennd approved these changes
Thanks so much for your patience on these!

2021-08-05 06:58 UTC, merged